const path = require("path");
const {
  CLAUDE_MD_FILE,
  CLAUDE_ROOT,
  FRAMEWORK_PACKAGE,
  FRAMEWORK_VERSION,
  LOCK_FILE,
  MANAGED_ROOT,
  STATE_ROOT,
  USER_CONFIG_FILE,
  VERSION_FILE,
} = require("./constants");
const {
  listExistingManagedFiles,
  normalizeRelativePath,
  readJsonIfExists,
  readTextIfExists,
  resolveRepoPath,
  writeTextFile,
} = require("./fs");
const { sha256 } = require("./hash");
const { stableStringify } = require("./json");

function renderManagedFiles({ cwd, config }) {
  const repoName = path.basename(cwd);
  const baseFiles = {
    [CLAUDE_MD_FILE]: `# ${repoName}

This repository uses a shared Claude Code bootstrap managed by ${FRAMEWORK_PACKAGE}.

## Working rules

- Treat \`.kyos/claude/\` as the managed source layer.
- Use \`.claude/\` as the repo-owned customization and override layer.
- Run \`npx kyos-cli --init\` to install or analyze the base structure.
- Run \`npx kyos-cli --apply\` after reviewing a proposal.
`,
    [normalizeRelativePath(path.join(MANAGED_ROOT, "commands", "README.md"))]:
      "# Managed Claude Commands\n\nThis folder is generated by kyos as the managed source layer. Override or extend behavior from `.claude/commands/`.\n",
    [normalizeRelativePath(path.join(MANAGED_ROOT, "commands", "project-context.md"))]:
      `# Project Context\n\nCapture architecture, key commands, and testing guidance for ${repoName} here.\n\n- Baseline: ${(config.extends || ["claude-base"]).join(", ")}\n- Framework version: ${FRAMEWORK_VERSION}\n`,
    [normalizeRelativePath(path.join(MANAGED_ROOT, "agents", "README.md"))]:
      "# Managed Claude Agents\n\nThis folder is generated by kyos. Put repo-specific agents in `.claude/agents/`.\n",
    [normalizeRelativePath(path.join(MANAGED_ROOT, "skills", "README.md"))]:
      "# Managed Claude Skills\n\nThis folder is generated by kyos. Put repo-specific skills in `.claude/skills/`.\n",
    [normalizeRelativePath(path.join(MANAGED_ROOT, "settings.json"))]:
      stableStringify({
        permissions: {
          defaultMode: "ask",
        },
        statusLine: {
          showBranch: true,
          showDirty: true,
        },
      }),
  };

  baseFiles[VERSION_FILE] = stableStringify({
    framework: FRAMEWORK_PACKAGE,
    managedRoot: MANAGED_ROOT,
    repoName,
    version: FRAMEWORK_VERSION,
  });

  return baseFiles;
}

function loadLock(cwd) {
  const lockPath = resolveRepoPath(cwd, LOCK_FILE);
  return (
    readJsonIfExists(lockPath) || {
      framework: FRAMEWORK_PACKAGE,
      version: FRAMEWORK_VERSION,
      files: {},
    }
  );
}

function planManagedChanges({ cwd, desiredFiles, currentLock }) {
  const results = [];
  const finalLockFiles = { ...(currentLock.files || {}) };

  for (const [relativePath, desiredContent] of Object.entries(desiredFiles)) {
    if (relativePath === LOCK_FILE) {
      continue;
    }

    const absolutePath = resolveRepoPath(cwd, relativePath);
    const currentContent = readTextIfExists(absolutePath);
    const currentChecksum = currentContent === null ? null : sha256(currentContent);
    const desiredChecksum = sha256(desiredContent);
    const lockEntry = currentLock.files ? currentLock.files[relativePath] : null;
    const lockedChecksum = lockEntry ? lockEntry.checksum : null;

    if (currentContent === null) {
      results.push({ action: "create", path: relativePath, content: desiredContent });
      finalLockFiles[relativePath] = { checksum: desiredChecksum, managed: true };
      continue;
    }

    if (currentChecksum === desiredChecksum) {
      results.push({ action: "ok", path: relativePath });
      finalLockFiles[relativePath] = { checksum: desiredChecksum, managed: true };
      continue;
    }

    if (!lockEntry) {
      results.push({
        action: "blocked",
        path: relativePath,
        reason: "unmanaged file already exists with different content",
      });
      continue;
    }

    if (currentChecksum !== lockedChecksum) {
      results.push({
        action: "conflict",
        path: relativePath,
        reason: "local changes detected; file was not overwritten",
      });
      finalLockFiles[relativePath] = lockEntry;
      continue;
    }

    results.push({ action: "update", path: relativePath, content: desiredContent });
    finalLockFiles[relativePath] = { checksum: desiredChecksum, managed: true };
  }

  return { results, finalLockFiles };
}

function applyManagedChanges({ cwd, plan }) {
  for (const item of plan.results) {
    if (item.action !== "create" && item.action !== "update") {
      continue;
    }

    writeTextFile(resolveRepoPath(cwd, item.path), item.content);
  }

  writeTextFile(
    resolveRepoPath(cwd, LOCK_FILE),
    stableStringify({
      framework: FRAMEWORK_PACKAGE,
      version: FRAMEWORK_VERSION,
      files: plan.finalLockFiles,
    })
  );
}

function findStaleManagedFiles(cwd, desiredFiles, currentLock) {
  const ignoredPaths = new Set([LOCK_FILE, USER_CONFIG_FILE]);
  const desiredPaths = new Set(
    Object.keys(desiredFiles).filter((pathName) => !ignoredPaths.has(pathName))
  );
  const stalePaths = [];

  for (const pathName of Object.keys(currentLock.files || {})) {
    if (!ignoredPaths.has(pathName) && !desiredPaths.has(pathName)) {
      stalePaths.push(pathName);
    }
  }

  for (const rootFolder of [STATE_ROOT, MANAGED_ROOT]) {
    for (const pathName of listExistingManagedFiles(cwd, rootFolder)) {
      if (!ignoredPaths.has(pathName) && !desiredPaths.has(pathName) && !stalePaths.includes(pathName)) {
        stalePaths.push(pathName);
      }
    }
  }

  return stalePaths.sort();
}

module.exports = {
  applyManagedChanges,
  findStaleManagedFiles,
  loadLock,
  planManagedChanges,
  renderManagedFiles,
};
